tasks:
  - init: |
      docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=genai -p 3306:3306 -d mysql:latest
      pip install -r requirements.txt
      python -c "from app.database import init_db; init_db()"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload